apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasper-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
      component: kasper-frontend
  template:
    metadata:
      labels:
        app: guestbook
        component: kasper-frontend
    spec:
      containers:
        - name: kasper-frontend
          image: ghcr.io/billare/guestbook-kasper-frontend:latest   #
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kasper-frontend
spec:
  type: ClusterIP
  selector:
    app: guestbook
    component: kasper-frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kasper-frontend
spec:
  to:
    kind: Service
    name: kasper-frontend
  port:
    targetPort: 8080
